name: postgres-replication-client

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: postgres -c wal_level=logical