name: postgres-replication-client

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_PASSWORD: "postgres"
      POSTGRESQL_POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
